- shell:
    - mkdir -p ~/Library/Music
    - mkdir -p ~/.config/alacritty
    - mkdir -p ~/Library/Application\ Support/Code/User

- link:
    ~/.config/alacritty/os.yaml: alacritty.yaml
    ~/Library/Music/Scripts: ../../music
    ~/Library/Application Support/Code/User/settings.json: ../../etc/vscode.json
