[package]
name    = "space"
version = "0.0.0"
authors = ["Casey Rodarmor <casey@rodarmor.com>"]
edition = "2018"

[dependencies]
serde_derive = "1.0.98"
serde        = "1.0.98"
serde_json   = "1.0.40"
structopt    = "0.2.18"
