[package]
name    = "shell"
version = "0.0.0"
authors = ["Casey Rodarmor <casey@rodarmor.com>"]
edition = "2018"

[dependencies]
csv          = "1.0.5"
serde        = "1.0.89"
serde_derive = "1.0.89"
tempfile     = "3.0.7"
