[package]
name    = "alfred-files"
version = "0.0.0"
authors = ["Casey Rodarmor <casey@rodarmor.com>"]
edition = "2018"

[dependencies]
serde_json = "1.0"
walkdir = "2.3.1"
dirs = "3.0.1"

[dependencies.serde]
version  = "1.0"
features = ["derive"]
